- name: draft
  hosts: new
  vars:
    userlist:
    - root
    - marekpl
    - krzysztofc
    homedirs:
    - /root
    - /home/marekpl
    - /home/krzysztofc

  tasks:

#   - name: hosts
#     template:
#       src: templates/hosts
#       dest: /etc/hosts
#       owner: root
#       group: root
#       mode: 0644
#     become: yes
#   - name: hostname
#     template:
#       src: templates/hostname
#       dest: /etc/hostname
#       owner: root
#       group: root
#       mode: 0644
#     become: yes

    - debug: msg="ssh daemon on {{ inventory_hostname }} should be restarted" verbosity=0
